import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./layout.scss";
import { Footer, Header } from "./component";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import ReduxProvider from "./ReduxStore/ReduxtProvider/ReduxProvider";

const Outfitfont = Outfit({
    subsets: ["latin"],
    weight: [
        '100', '200',
        '300', '400', '500', '600', '700'
    ]
});

export const metadata: Metadata = {
    title: "S-Shopping",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={Outfitfont.className}>
                <ReduxProvider>
                    <Header />
                    {children}
                    <Footer />
                </ReduxProvider>
            </body>
        </html>
    );
}
